#!/bin/bash
# Generated by LedgerView Assistant (MCP)

echo "Starting Canton Dev Network..."

# 1. Build your DAML models
echo "Building DAML models..."
daml build

# 2. Upload DAR to local participant
echo "Uploading DAR to localhost:6865..."
daml ledger upload-dar .daml/dist/*.dar --host localhost --port 6865

echo "Canton network ready!"
